"""added user refresh token

Revision ID: 86343b94c592
Revises: 2c5a9813081b
Create Date: 2026-07-09 09:13:36.649675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86343b94c592'
down_revision: Union[str, Sequence[str], None] = '2c5a9813081b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_refresh_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('user_refresh_token_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_refresh_token_expires_at')
    op.drop_column('users', 'user_refresh_token')
    # ### end Alembic commands ###
