"""move spotify access tokens to more descriptive field

Revision ID: ee7bbe01c730
Revises: 606003869ba6
Create Date: 2026-07-09 08:59:41.377851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee7bbe01c730'
down_revision: Union[str, Sequence[str], None] = '606003869ba6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('spotify_access_token', sa.String(), nullable=False))
    op.add_column('users', sa.Column('spotify_refresh_token', sa.String(), nullable=False))
    op.drop_column('users', 'refresh_token')
    op.drop_column('users', 'access_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('access_token', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('refresh_token', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('users', 'spotify_refresh_token')
    op.drop_column('users', 'spotify_access_token')
    # ### end Alembic commands ###
